let mapleader=" "
let $VIMHOME=expand("~/.vim")
set laststatus=2
set autoindent
set smartindent
set nocompatible
set shell=bash
set noswapfile
set backspace=indent,eol,start

source ~/.vim/comment.vim

colorscheme cold
syntax enable
set tabstop=8
set shiftwidth=8
set noexpandtab
set splitright
set wildmenu
set wildmode=list:full,full
set ignorecase
set smartcase

vmap <C-c> y:call system("xclip -i -selection clipboard", getreg("\""))<cr>:call system("xclip -i", getreg("\""))<cr>

noremap J o<esc>k
noremap K O<esc>j

noremap H ^
noremap L $
"move between pans"
nnoremap <Left>  <C-w>h
nnoremap <Down>  <C-w>j
nnoremap <Up> 	 <C-w>k
nnoremap <Right> <C-w>l
"move pans to"
nnoremap <Super><Left>  <C-w>H
nnoremap <Super><Down>  <C-w>J
nnoremap <Super><Up> 	 <C-w>K
nnoremap <Super><Right> <C-w>L
"move between tabs"
nnoremap <C-[>j		gT
nnoremap <C-[>k		gt

"------------------------------
"	    Plugins
"------------------------------
"execute pathogen#infect()
