"fonts"
set guifont=Monaco\ 14

"colorscheme"
colorscheme desert

"status line format
set statusline=%F%m%r%h%w\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]

"syntax highlighting"
syntax on

"show status bar"
set laststatus=2

"number lines"
set number
"set the number of digits for numbering lines"
set numberwidth=4

"map Capslock to exit INSERT mode from ESCAPE"
"map <CapsLock> 


"modification notes"
	":highlight		for changing any highlighting"
	":abbreviate		like #define"
	":map new old<cr>	<cr> for executing command, map different keybindes

