#!/bin/zsh

export ZDOTDIR="$HOME/.config/zsh"
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export ANDROID_HOME="$HOME/Android/Sdk"

export
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
export PATH="$PATH:$HOME/development-kit/android-studio/jre/bin"
export PATH="$PATH:/usr/share/nodejs/bin"
export PATH="$PATH:$HOME/development-kit/flutter/bin"
export PATH="$PATH:/usr/share/jdk/bin"
export PATH="$PATH:$HOME/.local/bin/statusbar"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
